spring:
  config:
    activate:
      on-profile: http
  main:
    web-application-type: servlet
    banner-mode: console
  ai:
    mcp:
      server:
        stdio: false
        name: mcp-conductor
        version: 1.0.0
        type: SYNC

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    net.alishahidi.mcpconductor: ${LOG_LEVEL:INFO}
    org.springframework.ai.mcp: ${MCP_LOG_LEVEL:DEBUG}